### PR TITLE
Feature/digital face

### PR DESCRIPTION
**Pull request by rawsignal**
This is probably not optimal. Not used to the world of C++ development.
I'm excluding the change to the main.cpp, if you want to use the digital watchface, you'll need to swap out OswAppWatchface for OswAppWatchfaceDigital until something is built to allow on-device changes

### CODE REVIEW

**Comment by uvwxy** [comment]
could you rebase your changes on top of the current master?

thank you

**Comment by rawsignal** [comment]
> could you rebase your changes on top of the current master?
> 
> thank you

Should be good now

**Comment by uvwxy** [comment]
Three things I noticed:

- lib/lib-open-smartwatch: what are the changes that you have in your commit?
- calculator: it's incomplete. I like the idea, but I guess this needs a separate, finished pull request
- time.cpp: could you add a define to config.h(.example) to enable 12H time, such that all uses of getLocalTime are either 12h or 24h (default)

thanks :)

**Comment by rawsignal** [comment]
> Three things I noticed:
> 
> * lib/lib-open-smartwatch: what are the changes that you have in your commit?
> * calculator: it's incomplete. I like the idea, but I guess this needs a separate, finished pull request
> * time.cpp: could you add a define to config.h(.example) to enable 12H time, such that all uses of getLocalTime are either 12h or 24h (default)
> 
> thanks :)
> 
> Edit: If you have questions, let me know.

The changes to lib/lib-open-smartwatch are strange...not sure what's going on there, but I'll have a look and undo it.
Calculator - will remove from PR
I can update getLocalTime to be 12 or 24 hour, config driven

**Comment by rawsignal** [comment]
I'm going to address these items in a new PR. Closing this one for now since I need some time to make the adjustments and I don't want this sitting around.

**Pull request closed without merging**
