### PR TITLE
Fixed Lightsleep not working properly

### PR DESCRIPTION
**Pull request by Gladox114**
Fixed Lightsleep not working properly with really really long enough button press as it switches to the next app because doSwitch is still true form LONG_PRESS.

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
Sorry close it. You can enable light sleep in the Web interface.

**Comment by Gladox114** [comment]
What do you mean with "You can enable light sleep in the Web interface"

**Comment by RuffaloLavoisier** [comment]
@Gladox114 
As far as I know, deep sleep and sleep mode can be adjusted through the web interface through the check box.

**Comment by simonmicro** [comment]
Lgtm

**Pull request merged**
