### PR TITLE
(Basic) support for Flow3r Badge (c3camp 2023)

### PR DESCRIPTION
**Pull request by simonmicro**
→ https://flow3r.garden/

Well, this not only adds the (basic) hardware support, but also (consequently) enhances and migrates the platform-abstraction layer to accommodate for the new hardware...

## Checklist / ToDo

- [x] Compile
- [x] First boot
- [x] Get display working (-> [datasheet](https://www.buydisplay.com/download/ic/GC9A01A.pdf))
- [x] WiFi
- [x] Buttons (for now, just the standard ones (up, down, select))
- [x] Add accelerometer support (BMI270)
- [ ] Add pressure support (BMP581)
    - [ ] :warning: This sensor is attached to the auxiliary I2C interface of the BMI270 - this significantly changes how to interact with that sensor, so direct I2C interface code cannot be used!
- [ ] ~~LEDs?~~ (better if devs add it when needed; for now too unique on this platform; hint: FastLED)
- [ ] ~~Capacitive Touch?~~ (better if devs add it when needed; for now too unique on this platform; hint: use the schematics and implement SPI driver for the GPIO extenders)
- [x] Get serial working properly  over the jtag-serial interface (because the usb-c sidechannel requires a special cable)

## Known Bugs
- [ ] If the badge enters sleep, you have to reset it → sleep is blocked for now via `OSW_PLATFORM_BLOCK_SLEEP`
  - [ ] ...currently the accelerometer-interrupt is not working, so the badge won't wake up upon tap
  - [ ] ...buttons and interrupts... Maybe we can also use them?

### CODE REVIEW

**Comment by schneider42** [comment]
Fails for me with:
```
Compiling .pio/build/FLOW3R_C3CAMP_2023/src/apps/OswAppDrawer.cpp.o
In file included from include/hal/devices.h:11,
                 from include/osw_hal.h:294,
                 from src/OswAppV2.cpp:1:
include/devices/bmi270.h:7:10: fatal error: bmi2_defs.h: No such file or directory

*******************************************************************
* Looking for bmi2_defs.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:bmi2_defs.h"
* Web  > https://registry.platformio.org/search?q=header:bmi2_defs.h
*
*******************************************************************

 #include <bmi2_defs.h>
          ^~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/FLOW3R_C3CAMP_2023/src/OswAppV2.cpp.o] Error 1
In file included from include/hal/devices.h:11,
                 from include/osw_hal.h:294,
                 from include/osw_ui.h:7,
                 from src/apps/OswAppDrawer.cpp:2:
include/devices/bmi270.h:7:10: fatal error: bmi2_defs.h: No such file or directory

*******************************************************************
* Looking for bmi2_defs.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:bmi2_defs.h"
* Web  > https://registry.platformio.org/search?q=header:bmi2_defs.h
*
*******************************************************************

 #include <bmi2_defs.h>
          ^~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/FLOW3R_C3CAMP_2023/src/apps/OswAppDrawer.cpp.o] Error 1
```

I did update the submodules

**Comment by schneider42** [comment]
I tried 72aa5463aa726ae87d5b5d230d8e3a0204103d79 (before BIM270 support gets introduced) and that builds and runs in principle:
signal-2023-08-26-190722_002
signal-2023-08-26-190722_003
signal-2023-08-26-190722_004

I was able to connect to the AP it opened up, but couldn't connect to the IP displayed using various ports. I'm a first time user and haven't read the docs though :)

**Comment by schneider42** [comment]
Connecting it to my home WiFi and showing the current time works (modulo me not understanding the timezone field)

**Comment by simonmicro** [comment]
Heyho, nice to hear!

So, regarding the missing header: Did you ensure to update _and initialize_ the submodules? So, did you run `git submodule sync; git submodule update --init`? Otherwise, maybe I've missed adding the repo.

Regarding the web interface problems: Take a look into the `platformio.ini` header and remove the `OSW_FEATURE_WIFI_APST` feature flag (allow simultaneous station and client mode). I assume this is causing the ESP-IDF framework to mess up the connection. Now the UI should load... Right?

**Comment by simonmicro** [comment]
Hey, I just pushed 71b8e1868d705ab40434497ca6df4f08083ca4fd - hopefully this fixes the broken submodule...

**Comment by simonmicro** [comment]
> Connecting it to my home WiFi and showing the current time works (modulo me not understanding the timezone field)

(inside the debug-app or inside the web-ui)?

**Pull request merged**
