### PR TITLE
Fix Auto sleep Timer on Watchface from Issue #186

### PR DESCRIPTION
**Pull request by techguytechtips**
I rewrote the auto sleep timeout so it will reset the sleep timer when any button is pressed on the main watch face, instead of only checking for button presses right before it goes to sleep.

This is my first pull request, apologies if I made it wrong.

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
See #186

**Review by RuffaloLavoisier — CHANGES_REQUESTED** [review]
PR is currently mixed with unnecessary commit history. Could you revise it (a8b10aafa3570be81c715d175ee3e91faf7558d9) again including this commit?

**Comment by techguytechtips** [comment]
> PR is currently mixed with unnecessary commit history. Could you revise it ([a8b10aa](https://github.com/Open-Smartwatch/open-smartwatch-os/commit/a8b10aafa3570be81c715d175ee3e91faf7558d9)) again including this commit?

should I commit my changes to the develop branch of my fork and then create a pull request instead?

**Comment by RuffaloLavoisier** [comment]
@techguytechtips 
Your current PR branch is Master. You can `git fetch` the current branch of PR to the latest `develop` branch and reflect the changes.

**Comment by techguytechtips** [comment]
> @techguytechtips Your current PR branch is Master. You can `git fetch` the current branch of PR to the latest `develop` branch and reflect the changes.

Ok so my master is up to date with develop (at least it should be) with by added changes which should fix the unneeded commit history hopefully.

**Comment by RuffaloLavoisier** [comment]
@techguytechtips 

Following me:
```
git checkout master
git remote add upstream https://github.com/Open-Smartwatch/open-smartwatch-os.git
git fetch upstream
git reset --hard upstream/develop
git cherry-pick a8b10aafa3570be81c715d175ee3e91faf7558d9
git push
```

**Comment by RuffaloLavoisier** [comment]
@techguytechtips 
Cool , great !

**Comment by techguytechtips** [comment]
> 

thank you for the step by step :)
like I said it was my first pull request so I was bound to make some sort of mistake.

**Review by simonmicro — APPROVED** [review]

**Comment by simonmicro** [comment]
@RuffaloLavoisier No need to request a review from yourself and then not making one :grin: 
Otherwise good work guys @RuffaloLavoisier @techguytechtips - thanks!

**Comment by RuffaloLavoisier** [comment]
I think we need test from this PR...next discuss !

**Pull request merged**
