### PR TITLE
Twist Wrist to Wake

### PR DESCRIPTION
**Pull request by rasppliances**
Added twist wrist to wake with changes to sensors.cpp and power.cpp

### CODE REVIEW

**Comment by uvwxy** [comment]
I will take a look at this today, but I'll merge it into develop first.

**Comment by xasz** [comment]
@rasppliances Nice work
Seems to work fine. I cannot tell if this is the right way todo, because i do not know about the hardware much, but it works.
I think there need to be some playing aroung with the threshold because i think it feels very low.

What i did't not understand is this in the sensors.cpp?
Is this a copy paste error?

`rslt = bma400_get_sensor_conf(accel_setting, 3, &bma);
  bma400_check_rslt("bma400_get_sensor_conf", rslt);
  rslt = bma400_get_sensor_conf(accel_setting, 3, &bma);
  bma400_check_rslt("bma400_get_sensor_conf", rslt);`

**Comment by rasppliances** [comment]
@xasz Thanks!

The threshold certainly is flexible.  In my testing it was OK, but it was an arbitrary number.  I also didn't test it on my right wrist, so that might make a difference.

That code is a copy paste error.  I don't know why I didn't see that.

**Comment by uvwxy** [comment]
I cherry picked your commit: 9987773

**Pull request closed without merging**
