### PR TITLE
Italian translation of default locale

### PR DESCRIPTION
**Pull request by thet3o**
This is the translation of default locale en-US.h to italian

### CODE REVIEW

**Comment by Simonmicro** [comment]
Could you explain what 5556068672c5fd43ff327585c9969af1a3673cda has to do with the new language file?

**Comment by thet3o** [comment]
Sorry it's an error, I'm trying to revert it

**Comment by Simonmicro** [comment]
Okay this is getting out-of hand.
Please run:
```bash
git fetch
git checkout origin/develop
git branch -d develop
git checkout develop
git cherry-pick 6f91fc9a498f289367849a7361b064a7e8965200 
git push --force origin develop
```
...assuming `origin` refers to your fork.

**Comment by Simonmicro** [comment]
This will allow you to ONLY commit your work on the translations - as your current revert-commits do not work (?!?), the files are still shown as modified.
I hope this helps to get a clean PR.

**Comment by thet3o** [comment]
Thanks!

**Comment by thet3o** [comment]
I've got this error :
"error: src refspec develop does not match any
error: failed to push some refs to 'https://github.com/thet3o/open-smartwatch-os.git'"

**Comment by thet3o** [comment]
Can I try to use github desktop drag and dropping the commit directly to the upstream/develop?

**Comment by Simonmicro** [comment]
I've cherry-picked and pushed the respective commit myself - check it out on `develop`.

Thanks!

**Pull request closed without merging**
