### PR TITLE
Apps/watchfaces : fix overlap in Watchface

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
* Improved stepHistory-frame and stepHistory-Arc overlap in `Watchface.cpp`.
* Improve the areas that are disturbed by the background of the text.

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
@simonmicro 
Please submodule update the library.. :smile:

**Comment by simonmicro** [comment]
@RuffaloLavoisier Please update the submodule with an own commit yourself, as I do not have any access to your private fork.

**Comment by RuffaloLavoisier** [comment]
@simonmicro 

https://github.com/Open-Smartwatch/lib-open-smartwatch/commit/326bac8aca7c12bdd7a71dd6549ffa3c4628a992

This part is not currently reflected in the [main repository](https://github.com/Open-Smartwatch/lib-open-smartwatch/blob/3ba71a10065080d784248a96eefd124a493cd311/gfx_2d_print.h#L440).

Currently, the submodule of the main repository has not been updated. If you update the submodule to the main repository, I will correct it through fetch and merge operations.

**Comment by simonmicro** [comment]
I think you did not fully understand the concept of submodules? Of course, may I did not understand you correctly?
If you would run...
```bash
git submodule update --remote lib/lib-open-smartwatch
git commit lib/lib-open-smartwatch
```
...this would fetch the current master of the submodule into the folder and then commit the new hash of the submodule into your branch. As far I recall that should be it?

**Comment by RuffaloLavoisier** [comment]
@simonmicro 
Done, is it okay if someone else besides the main administrator promotes the submodule in the latest state?

**Comment by RuffaloLavoisier** [comment]
@simonmicro 
Build success ! thanks

**Pull request merged**
