### PR TITLE
CI : update parallel compile from language resolve #217

### LINKED ISSUE #217: Improve the CI (FAST)
It's not a long time, but we want to speed up and increase efficiency in the development process.  
* if  end of coffee time then finish !
* [x] https://github.com/Open-Smartwatch/open-smartwatch-os/pull/219
* [x] https://github.com/Open-Smartwatch/open-smartwatch-os/pull/221

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
Oops.....there seems to be a problem with the submodule.

**Comment by RuffaloLavoisier** [comment]
Amazing...I shortened it to 16 minutes...

**Comment by RuffaloLavoisier** [comment]
In this way, we expect that all models can also be compiled in parallel to reduce to *1 minute* increments.  The downside is that you can't just automation-read the model or language and you have to input it every time it's updated or added.

**Comment by RuffaloLavoisier** [comment]
Ddddd....why isn't the CI pipeline working?

**Review by simonmicro — CHANGES_REQUESTED** [review]
My only request would be to add a `README.md` beside the locale headers, so any dev who adds a new language gets reminded to also extend the GitHub Actions pipeline.

**Review by simonmicro — APPROVED** [review]

**Pull request merged**
